version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn packege
  post_build:
    commands:
      - echo Building, Testing and packaging the application.
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'